# Generated by Django 5.0.4 on 2024-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='business_user_permissions', to='auth.permission'),
        ),
    ]
